name: extendable_fab
description: A floating action button that can animate between icon only and extended fab
version: 1.0.0
author: HrX03
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: